- hosts: all
  tasks:
          - name: install http
            yum: 
               name:
                       - httpd
                       - firewalld
               state: installed
          - name: enabling firewal
            service:
                    name: firewalld 
                    state: started
                    enabled: true

          - name: allowing http over firewall
            firewalld:
                 service: http
                 permanent: yes
                 state: enabled
                 immediate: true

          - name: content
            lineinfile:
                    line: Welcome Hello
                    path: /var/www/html/index.html
                    state: present
          - name: start http service and enabled
            service:
                    name: httpd
                    state: started
                    enabled: true
